org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.235
loader_version_range=[1,)

mod_id=passwordgate
mod_name=PasswordGate
mod_license=Apache-2.0
mod_version=1.0.0
mod_group_id=org.wodichka
mod_authors=waterflane
mod_description=Configuration-phase SRP-6a password authentication for Minecraft servers.
